name: banrep
channels:
  - defaults
dependencies:
  - cython=0.29.7
  - gensim=3.4.0
  - jupyterlab=0.35.5
  - lxml=4.3.3
  - matplotlib=3.0.3
  - numpy=1.16.3
  - pandas=0.24.2
  - pip=19.1
  - python=3.7.3
  - requests=2.21.0
  - scipy=1.2.1
  - seaborn=0.9.0
  - xlrd=1.2.0
  - pip:
    - dash==0.42.0
    - jsonlines==1.2.0
    - plotly==3.8.1
    - pytest==4.4.2
    - spacy==2.1.3
    - tika==1.19
