name: banrep
channels:
  - defaults
dependencies:
  - cython=0.29.14
  - gensim=3.8.1
  - jupyterlab=1.2.6
  - lxml=4.5.0
  - matplotlib=3.1.3
  - numpy=1.17.5
  - pandas=1.0.0
  - pip=19.1
  - python=3.7.3
  - scipy=1.4.1
  - xlrd=1.2.0
  - pip:
    - plotly==4.5.0
    - pytest==5.3.4
    - spacy==2.2.3
    - tika==1.19
